"""
Django settings for musicbeta project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env_file(base_dir):
    """Load simple KEY=VALUE pairs from .env into process env if unset."""
    env_file = base_dir / '.env'
    if not env_file.exists():
        return

    for raw_line in env_file.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            # Let local .env control project-specific settings consistently.
            os.environ[key] = value


_load_local_env_file(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l+^mh0yyrm2n_5znhcj-2lf2qu98xpl%@wum)^pga%w$ruy_(#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'finder',
    'crispy_forms',
    'crispy_bootstrap5',
     'rest_framework',
]
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'musicbeta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'musicbeta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
# After successful login, send users to the public home page
LOGIN_REDIRECT_URL = 'home'
# After logout send users to the login page
LOGOUT_REDIRECT_URL = 'login'

# Khalti configuration (supports sandbox/live)
KHALTI_MODE = os.environ.get('KHALTI_MODE', 'sandbox').strip().lower()

_khalti_default_base_url = (
    'https://khalti.com' if KHALTI_MODE == 'live' else 'https://dev.khalti.com'
)

def _get_first_env_value(*names):
    for name in names:
        value = (os.environ.get(name, '') or '').strip()
        if value:
            return value
    return ''


if KHALTI_MODE == 'live':
    KHALTI_PUBLIC_KEY = _get_first_env_value('KHALTI_LIVE_PUBLIC_KEY', 'KHALTI_PUBLIC_KEY')
    KHALTI_SECRET_KEY = _get_first_env_value('KHALTI_LIVE_SECRET_KEY', 'KHALTI_SECRET_KEY')
else:
    KHALTI_PUBLIC_KEY = _get_first_env_value('KHALTI_SANDBOX_PUBLIC_KEY', 'KHALTI_PUBLIC_KEY')
    KHALTI_SECRET_KEY = _get_first_env_value('KHALTI_SANDBOX_SECRET_KEY', 'KHALTI_SECRET_KEY')

KHALTI_INITIATE_URL = os.environ.get(
    'KHALTI_INITIATE_URL',
    f'{_khalti_default_base_url}/api/v2/epayment/initiate/',
)
KHALTI_LOOKUP_URL = os.environ.get(
    'KHALTI_LOOKUP_URL',
    f'{_khalti_default_base_url}/api/v2/epayment/lookup/',
)

KHALTI_WEBSITE_URL = os.environ.get('KHALTI_WEBSITE_URL', '').strip()
KHALTI_RETURN_URL_BASE = os.environ.get('KHALTI_RETURN_URL_BASE', '').strip()

# Simple premium subscription configuration
SUBSCRIPTION_PRICE_NPR = int(os.environ.get('SUBSCRIPTION_PRICE_NPR', '999'))
SUBSCRIPTION_DURATION_DAYS = int(os.environ.get('SUBSCRIPTION_DURATION_DAYS', '30'))

# Operations admin credentials are intentionally loaded from the environment so
# they are not embedded in source control.
OPS_ADMIN_USERNAME = os.environ.get('OPS_ADMIN_USERNAME', '').strip()
OPS_ADMIN_PASSWORD = os.environ.get('OPS_ADMIN_PASSWORD', '').strip()

# Jamendo API client id for open source music search
JAMENDO_CLIENT_ID = os.environ.get('JAMENDO_CLIENT_ID', '56d30c95').strip()

# Jellyfin (self-hosted) source configuration
JELLYFIN_SERVER_URL = os.environ.get('JELLYFIN_SERVER_URL', '').strip()
JELLYFIN_API_KEY = os.environ.get('JELLYFIN_API_KEY', '').strip()
JELLYFIN_USER_ID = os.environ.get('JELLYFIN_USER_ID', '').strip()

# SMTP email configuration (used for payment receipts)
# Sensitive credentials should be set via environment variables
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
