# Generated by Django 5.2.8 on 2026-01-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_alter_playlist_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.CharField(choices=[('local', 'Local Upload'), ('jamendo', 'Jamendo'), ('itunes', 'iTunes')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finder.genre'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('external_id', 'source')},
        ),
    ]
