# Generated by Django 5.2.8 on 2026-03-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_song_audio_url_song_cover_image_url_song_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='source',
            field=models.CharField(choices=[('local', 'Local Upload'), ('jamendo', 'Jamendo'), ('itunes', 'iTunes'), ('opensource', 'Open Source Music')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=200),
        ),
    ]
