# Generated by Django 5.2.2 on 2026-04-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_playlist_is_auto_generated_playlist_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to='finder.song'),
        ),
    ]
