# Generated by Django 5.2.2 on 2026-04-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_alter_listeninghistory_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.IntegerField(default=30, help_text='Subscription duration in days')),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(help_text='Features separated by newlines')),
                ('max_playlists', models.IntegerField(default=3)),
                ('max_songs_per_playlist', models.IntegerField(default=5)),
                ('ad_free', models.BooleanField(default=False)),
                ('download_available', models.BooleanField(default=False)),
                ('offline_mode', models.BooleanField(default=False)),
                ('hd_audio', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='finder.subscriptionplan'),
        ),
    ]
