# Generated by Django 5.2.8 on 2026-04-03 15:59

from django.db import migrations, models


def normalize_trial_subscriptions(apps, schema_editor):
    Subscription = apps.get_model('finder', 'Subscription')
    SubscriptionPlan = apps.get_model('finder', 'SubscriptionPlan')
    free_plan = SubscriptionPlan.objects.filter(tier='free').first()

    for subscription in Subscription.objects.filter(tier='trial'):
        subscription.tier = 'free'
        subscription.expiry_date = None
        if free_plan:
            subscription.plan = free_plan
        subscription.save(update_fields=['tier', 'expiry_date', 'plan'])


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_subscriptionchangelog'),
    ]

    operations = [
        migrations.RunPython(normalize_trial_subscriptions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_end_date',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
