# Generated by Django 5.2.2 on 2026-04-15 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0013_adminactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='source',
            field=models.CharField(choices=[('local', 'Local Upload'), ('itunes', 'iTunes')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('source_filter', models.CharField(blank=True, default='', max_length=20)),
                ('genre_filter', models.CharField(blank=True, default='', max_length=100)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('results_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', '-searched_at'], name='finder_sear_user_id_3156e6_idx'), models.Index(fields=['query', '-searched_at'], name='finder_sear_query_9e2d5a_idx')],
            },
        ),
    ]
