# Generated by Django 5.2.8 on 2026-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0014_alter_song_source_alter_subscription_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20),
        ),
    ]
